swagger: '2.0'
info:
  title: {{title}}
  description: ''
  version: '1'
schemes:
  - {{scheme}}
host: {{host}}
basePath: {{basePath}}
produces:
  - application/json
  - text/html
{{parameters}}
{{paths}}
{{definitions}}